export const courses = [
  // === PEMASARAN ===
  {
    id: "1",
    title: "Big 4 Auditor Financial Analyst",
    instructor: "Jenna Ortega\nSenior Accountant",
    price: 300,
    rating: "3.5 (68)",
    image: "/thumbnail/satu.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Fundamental Analisis Keuangan Perusahaan",
        type: "Video",
        duration: "15 Menit",
        expanded: true,
        items: [
          { title: "Memahami laporan keuangan dasar", type: "Video", duration: "10 Menit" },
          { title: "Analisis rasio keuangan penting", type: "Video", duration: "18 Menit" },
          { title: "Studi kasus perusahaan publik", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Tools Audit Modern",
        type: "Video",
        duration: "14 Menit",
      },
      {
        title: "Membuat Laporan Audit Profesional",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "2",
    title: "Strategi Digital Marketing 2024",
    instructor: "Reza Mahendra\nDigital Marketer",
    price: 250,
    rating: "4.2 (120)",
    image: "/thumbnail/dua.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Landscape Digital Marketing Terkini",
        type: "Video",
        duration: "16 Menit",
        expanded: true,
        items: [
          { title: "Trend platform digital 2024", type: "Video", duration: "12 Menit" },
          { title: "Perubahan algoritma media sosial", type: "Video", duration: "14 Menit" },
          { title: "Strategi konten multi-platform", type: "Video", duration: "18 Menit" },
        ],
      },
      {
        title: "Membangun Buyer Persona",
        type: "Video",
        duration: "19 Menit",
      },
      {
        title: "Optimasi Funnel Konversi",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "3",
    title: "Mastering SEO & SEM",
    instructor: "Alia Fauzia\nSEO Expert",
    price: 200,
    rating: "4.0 (87)",
    image: "/thumbnail/tiga.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Dasar-dasar Optimasi Mesin Pencari",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Penelitian kata kunci efektif", type: "Video", duration: "15 Menit" },
          { title: "Technical SEO untuk pemula", type: "Video", duration: "17 Menit" },
          { title: "Membangun backlink berkualitas", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Google Ads dari Nol",
        type: "Video",
        duration: "25 Menit",
      },
      {
        title: "Analisis Kompetitor SEO",
        type: "Video",
        duration: "18 Menit",
      },
    ],
  },
  {
    id: "4",
    title: "Branding & Positioning Expert",
    instructor: "Dewi Lestari\nBrand Strategist",
    price: 270,
    rating: "4.3 (93)",
    image: "/thumbnail/empat.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Membangun Identitas Merek Kuat",
        type: "Video",
        duration: "20 Menit",
        expanded: true,
        items: [
          { title: "Proses penentuan positioning", type: "Video", duration: "14 Menit" },
          { title: "Menciptakan brand voice", type: "Video", duration: "16 Menit" },
          { title: "Studi kasus rebranding sukses", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Strategi Differensiasi Merek",
        type: "Video",
        duration: "18 Menit",
      },
      {
        title: "Brand Archetypes Psychology",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "5",
    title: "Data-Driven Marketing Analytics",
    instructor: "Taufik Hidayat\nMarketing Analyst",
    price: 280,
    rating: "4.4 (101)",
    image: "/thumbnail/lima.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Panduan Google Analytics 4",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "Setup dan konfigurasi GA4", type: "Video", duration: "15 Menit" },
          { title: "Membaca dashboard analytics", type: "Video", duration: "18 Menit" },
          { title: "Membuat custom report", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Data Visualization untuk Marketer",
        type: "Video",
        duration: "17 Menit",
      },
      {
        title: "ROI Analysis Techniques",
        type: "Video",
        duration: "19 Menit",
      },
    ],
  },
  {
    id: "6",
    title: "Email Marketing Automation Pro",
    instructor: "Karina Putri\nCampaign Specialist",
    price: 210,
    rating: "4.1 (72)",
    image: "/thumbnail/enam.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Membangun Daftar Email Berkualitas",
        type: "Video",
        duration: "18 Menit",
        expanded: true,
        items: [
          { title: "Strategi lead magnet efektif", type: "Video", duration: "14 Menit" },
          { title: "Optimasi landing page", type: "Video", duration: "16 Menit" },
          { title: "Segmentasi audiens canggih", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Workflow Automation dengan Mailchimp",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Copywriting untuk Email Marketing",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "7",
    title: "Content Marketing Masterclass",
    instructor: "Ari Wibowo\nContent Strategist",
    price: 230,
    rating: "4.0 (89)",
    image: "/thumbnail/tujuh.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Membangun Content Strategy",
        type: "Video",
        duration: "21 Menit",
        expanded: true,
        items: [
          { title: "Content audit dan gap analysis", type: "Video", duration: "15 Menit" },
          { title: "Content calendar profesional", type: "Video", duration: "17 Menit" },
          { title: "Repurposing content multi-platform", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Storytelling untuk Branding",
        type: "Video",
        duration: "18 Menit",
      },
      {
        title: "SEO Content Writing Teknik",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "8",
    title: "Facebook & Instagram Ads Expert",
    instructor: "Lisa Andini\nAds Specialist",
    price: 260,
    rating: "3.9 (77)",
    image: "/thumbnail/delapan.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Membuat Campaign yang Convert",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "Struktur campaign optimal", type: "Video", duration: "16 Menit" },
          { title: "Targeting audiens presisi", type: "Video", duration: "18 Menit" },
          { title: "Creative testing framework", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Advanced Bidding Strategies",
        type: "Video",
        duration: "19 Menit",
      },
      {
        title: "Analisis dan Optimasi Iklan",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "9",
    title: "TikTok Marketing Revolution",
    instructor: "Nina Saputra\nSocial Media Expert",
    price: 250,
    rating: "4.2 (84)",
    image: "/thumbnail/sembilan.jpeg",
    category: "Pemasaran",
    video: [
      {
        title: "Algoritma TikTok Terkini",
        type: "Video",
        duration: "20 Menit",
        expanded: true,
        items: [
          { title: "Memahami For You Page", type: "Video", duration: "14 Menit" },
          { title: "Jenis konten viral TikTok", type: "Video", duration: "16 Menit" },
          { title: "Strategi hashtag efektif", type: "Video", duration: "18 Menit" },
        ],
      },
      {
        title: "TikTok Ads untuk Bisnis",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Membangun Komunitas di TikTok",
        type: "Video",
        duration: "19 Menit",
      },
    ],
  },

  // === DESAIN ===
  {
    id: "10",
    title: "UI/UX Design Fundamental",
    instructor: "Dian Kartika\nUI/UX Designer",
    price: 320,
    rating: "4.5 (134)",
    image: "/thumbnail/satu.jpeg",
    category: "Desain",
    video: [
      {
        title: "Prinsip Dasar User Experience",
        type: "Video",
        duration: "18 Menit",
        expanded: true,
        items: [
          { title: "User-centered design approach", type: "Video", duration: "12 Menit" },
          { title: "Information architecture basics", type: "Video", duration: "15 Menit" },
          { title: "Wireframing techniques", type: "Video", duration: "17 Menit" },
        ],
      },
      {
        title: "UX Research Methods",
        type: "Video",
        duration: "20 Menit",
      },
      {
        title: "Prototyping dengan Figma",
        type: "Video",
        duration: "22 Menit",
      },
    ],
  },
  {
    id: "11",
    title: "Adobe Photoshop Professional",
    instructor: "Kevin Santoso\nGraphic Designer",
    price: 300,
    rating: "4.3 (102)",
    image: "/thumbnail/dua.jpeg",
    category: "Desain",
    video: [
      {
        title: "Workshop Retouching Foto",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "Tools retouching esensial", type: "Video", duration: "16 Menit" },
          { title: "Teknik skin retouching", type: "Video", duration: "18 Menit" },
          { title: "Color grading profesional", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Digital Painting Dasar",
        type: "Video",
        duration: "21 Menit",
      },
      {
        title: "Komposisi Desain Advanced",
        type: "Video",
        duration: "19 Menit",
      },
    ],
  },
  {
    id: "12",
    title: "Canva untuk Profesional",
    instructor: "Putri Ayu\nCreative Designer",
    price: 150,
    rating: "4.1 (88)",
    image: "/thumbnail/tiga.jpeg",
    category: "Desain",
    video: [
      {
        title: "Memaksimalkan Canva Pro",
        type: "Video",
        duration: "17 Menit",
        expanded: true,
        items: [
          { title: "Fitur premium Canva", type: "Video", duration: "12 Menit" },
          { title: "Brand kit customization", type: "Video", duration: "14 Menit" },
          { title: "Magic resize teknik", type: "Video", duration: "16 Menit" },
        ],
      },
      {
        title: "Desain Sosmed yang Konsisten",
        type: "Video",
        duration: "19 Menit",
      },
      {
        title: "Animasi Dasar di Canva",
        type: "Video",
        duration: "18 Menit",
      },
    ],
  },
  {
    id: "13",
    title: "Vector Illustration Mastery",
    instructor: "Yoga Pratama\nVector Artist",
    price: 275,
    rating: "4.4 (93)",
    image: "/thumbnail/empat.jpeg",
    category: "Desain",
    video: [
      {
        title: "Adobe Illustrator Crash Course",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Pen tool mastery", type: "Video", duration: "15 Menit" },
          { title: "Creating custom brushes", type: "Video", duration: "17 Menit" },
          { title: "Advanced path techniques", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Flat Illustration Style",
        type: "Video",
        duration: "20 Menit",
      },
      {
        title: "Isometric Design Workshop",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "14",
    title: "Portofolio Desain Digital",
    instructor: "Indah Lestari\nVisual Designer",
    price: 220,
    rating: "4.2 (77)",
    image: "/thumbnail/lima.jpeg",
    category: "Desain",
    video: [
      {
        title: "Membangun Portofolio Menarik",
        type: "Video",
        duration: "19 Menit",
        expanded: true,
        items: [
          { title: "Seleksi karya terbaik", type: "Video", duration: "14 Menit" },
          { title: "Storytelling dalam portofolio", type: "Video", duration: "16 Menit" },
          { title: "Platform portofolio online", type: "Video", duration: "18 Menit" },
        ],
      },
      {
        title: "Presentasi Kreatif Projek",
        type: "Video",
        duration: "17 Menit",
      },
      {
        title: "Personal Branding untuk Desainer",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "15",
    title: "Design Thinking Workshop",
    instructor: "Rian Hidayat\nProduct Designer",
    price: 260,
    rating: "4.0 (81)",
    image: "/thumbnail/enam.jpeg",
    category: "Desain",
    video: [
      {
        title: "Proses Design Thinking Lengkap",
        type: "Video",
        duration: "21 Menit",
        expanded: true,
        items: [
          { title: "Empathize phase techniques", type: "Video", duration: "15 Menit" },
          { title: "Ideation methods", type: "Video", duration: "17 Menit" },
          { title: "Prototyping cepat", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "User Testing Strategies",
        type: "Video",
        duration: "18 Menit",
      },
      {
        title: "Implementasi di Dunia Nyata",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "16",
    title: "Figma untuk Tim",
    instructor: "Aditya Saputra\nUI Specialist",
    price: 310,
    rating: "4.5 (97)",
    image: "/thumbnail/tujuh.jpeg",
    category: "Desain",
    video: [
      {
        title: "Collaborative Design Workflow",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "Design system setup", type: "Video", duration: "16 Menit" },
          { title: "Component libraries", type: "Video", duration: "18 Menit" },
          { title: "Version control best practices", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Handoff ke Developer",
        type: "Video",
        duration: "19 Menit",
      },
      {
        title: "Plugin Figma Produktif",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "17",
    title: "Mobile UI Design Patterns",
    instructor: "Aulia Rachma\nUI/UX Freelancer",
    price: 290,
    rating: "4.3 (88)",
    image: "/thumbnail/delapan.jpeg",
    category: "Desain",
    video: [
      {
        title: "iOS vs Android Guidelines",
        type: "Video",
        duration: "20 Menit",
        expanded: true,
        items: [
          { title: "Human interface principles", type: "Video", duration: "14 Menit" },
          { title: "Material design system", type: "Video", duration: "16 Menit" },
          { title: "Cross-platform considerations", type: "Video", duration: "18 Menit" },
        ],
      },
      {
        title: "Microinteractions Design",
        type: "Video",
        duration: "17 Menit",
      },
      {
        title: "Mobile Navigation Paradigms",
        type: "Video",
        duration: "19 Menit",
      },
    ],
  },
  {
    id: "18",
    title: "Typography & Layout Mastery",
    instructor: "Niko Prasetyo\nPrint Designer",
    price: 240,
    rating: "4.1 (79)",
    image: "/thumbnail/sembilan.jpeg",
    category: "Desain",
    video: [
      {
        title: "Prinsip Tipografi Modern",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Font pairing techniques", type: "Video", duration: "15 Menit" },
          { title: "Hierarchy visual", type: "Video", duration: "17 Menit" },
          { title: "Responsive typography", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Grid Systems Workshop",
        type: "Video",
        duration: "20 Menit",
      },
      {
        title: "Print vs Digital Layout",
        type: "Video",
        duration: "18 Menit",
      },
    ],
  },

  // === PENGEMBANGAN DIRI ===
  {
    id: "19",
    title: "Modern Web Development",
    instructor: "Agus Riyadi\nWeb Developer",
    price: 280,
    rating: "4.4 (103)",
    image: "/thumbnail/satu.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "HTML5 & CSS3 Terkini",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "Semantic HTML", type: "Video", duration: "16 Menit" },
          { title: "CSS Grid & Flexbox", type: "Video", duration: "18 Menit" },
          { title: "Responsive design patterns", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "JavaScript ES6+ Fundamentals",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Debugging Techniques",
        type: "Video",
        duration: "19 Menit",
      },
    ],
  },
  {
    id: "20",
    title: "React.js Fundamental",
    instructor: "Siti Rahma\nFrontend Engineer",
    price: 300,
    rating: "4.3 (100)",
    image: "/thumbnail/dua.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Konsep Dasar React",
        type: "Video",
        duration: "21 Menit",
        expanded: true,
        items: [
          { title: "JSX dan Virtual DOM", type: "Video", duration: "15 Menit" },
          { title: "Components dan Props", type: "Video", duration: "17 Menit" },
          { title: "State dan Lifecycle", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Hooks Revolution",
        type: "Video",
        duration: "23 Menit",
      },
      {
        title: "React Router v6",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "21",
    title: "Android Dev dengan Kotlin",
    instructor: "Dimas Prakoso\nMobile Dev",
    price: 320,
    rating: "4.5 (120)",
    image: "/thumbnail/tiga.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Kotlin untuk Pemula",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Syntax dasar Kotlin", type: "Video", duration: "16 Menit" },
          { title: "Null safety", type: "Video", duration: "18 Menit" },
          { title: "Extension functions", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Android Studio Mastery",
        type: "Video",
        duration: "24 Menit",
      },
      {
        title: "Membangun UI dengan Jetpack Compose",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "22",
    title: "Laravel 10 Fundamental",
    instructor: "Budi Santosa\nBackend Developer",
    price: 290,
    rating: "4.2 (89)",
    image: "/thumbnail/empat.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Arsitektur Laravel",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "MVC pattern", type: "Video", duration: "17 Menit" },
          { title: "Routing dan Middleware", type: "Video", duration: "19 Menit" },
          { title: "Eloquent ORM", type: "Video", duration: "21 Menit" },
        ],
      },
      {
        title: "Authentication System",
        type: "Video",
        duration: "20 Menit",
      },
      {
        title: "API Development",
        type: "Video",
        duration: "22 Menit",
      },
    ],
  },
  {
    id: "23",
    title: "Data Science dengan Python",
    instructor: "Laras Widya\nData Analyst",
    price: 310,
    rating: "4.6 (130)",
    image: "/thumbnail/lima.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Python untuk Analisis Data",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "Pandas fundamentals", type: "Video", duration: "18 Menit" },
          { title: "Data cleaning techniques", type: "Video", duration: "20 Menit" },
          { title: "Visualisasi dengan Matplotlib", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Statistik untuk Data Science",
        type: "Video",
        duration: "25 Menit",
      },
      {
        title: "Machine Learning Pengenalan",
        type: "Video",
        duration: "23 Menit",
      },
    ],
  },
  {
    id: "24",
    title: "Git & GitHub Professional",
    instructor: "Eko Susilo\nDevOps",
    price: 200,
    rating: "4.0 (75)",
    image: "/thumbnail/enam.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Version Control Fundamental",
        type: "Video",
        duration: "19 Menit",
        expanded: true,
        items: [
          { title: "Setup dan konfigurasi Git", type: "Video", duration: "14 Menit" },
          { title: "Basic Git commands", type: "Video", duration: "16 Menit" },
          { title: "Branching strategy", type: "Video", duration: "18 Menit" },
        ],
      },
      {
        title: "Collaboration Workflows",
        type: "Video",
        duration: "21 Menit",
      },
      {
        title: "GitHub Actions CI/CD",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "25",
    title: "Advanced JavaScript Patterns",
    instructor: "Farah Lestari\nSoftware Engineer",
    price: 270,
    rating: "4.1 (91)",
    image: "/thumbnail/tujuh.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Modern JavaScript Features",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "ES6+ syntax", type: "Video", duration: "16 Menit" },
          { title: "Async/await pattern", type: "Video", duration: "18 Menit" },
          { title: "Modules system", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Design Patterns in JS",
        type: "Video",
        duration: "24 Menit",
      },
      {
        title: "Performance Optimization",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "26",
    title: "Machine Learning Fundamental",
    instructor: "Rizky Hadi\nML Engineer",
    price: 350,
    rating: "4.7 (140)",
    image: "/thumbnail/delapan.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Konsep Dasar Machine Learning",
        type: "Video",
        duration: "25 Menit",
        expanded: true,
        items: [
          { title: "Supervised vs unsupervised", type: "Video", duration: "18 Menit" },
          { title: "Feature engineering", type: "Video", duration: "20 Menit" },
          { title: "Model evaluation metrics", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Scikit-learn Workshop",
        type: "Video",
        duration: "23 Menit",
      },
      {
        title: "Neural Networks Pengenalan",
        type: "Video",
        duration: "24 Menit",
      },
    ],
  },
  {
    id: "27",
    title: "REST API Development",
    instructor: "Anita Zahra\nBackend Specialist",
    price: 285,
    rating: "4.3 (99)",
    image: "/thumbnail/sembilan.jpeg",
    category: "Pengembangan Diri",
    video: [
      {
        title: "Arsitektur REST API",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "HTTP methods dan status codes", type: "Video", duration: "16 Menit" },
          { title: "Endpoint design", type: "Video", duration: "18 Menit" },
          { title: "Authentication methods", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Documentasi dengan Swagger",
        type: "Video",
        duration: "19 Menit",
      },
      {
        title: "Performance Optimization",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },

  // === BISNIS ===
  {
    id: "28",
    title: "Business Model Innovation",
    instructor: "Michael Tan\nBusiness Consultant",
    price: 290,
    rating: "4.4 (95)",
    image: "/thumbnail/satu.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Business Model Canvas",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "9 elemen BMC", type: "Video", duration: "17 Menit" },
          { title: "Value proposition design", type: "Video", duration: "19 Menit" },
          { title: "Revenue streams innovation", type: "Video", duration: "21 Menit" },
        ],
      },
      {
        title: "Lean Startup Methodology",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Case Study: Startups Sukses",
        type: "Video",
        duration: "24 Menit",
      },
    ],
  },
  {
    id: "29",
    title: "Financial Planning Expert",
    instructor: "Sarah Wijaya\nFinancial Planner",
    price: 310,
    rating: "4.5 (110)",
    image: "/thumbnail/dua.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Personal Finance Management",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "Budgeting techniques", type: "Video", duration: "18 Menit" },
          { title: "Debt management", type: "Video", duration: "20 Menit" },
          { title: "Investment planning", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Retirement Planning",
        type: "Video",
        duration: "23 Menit",
      },
      {
        title: "Tax Optimization Strategies",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "30",
    title: "Digital Entrepreneurship",
    instructor: "Andi Setiawan\nStartup Founder",
    price: 270,
    rating: "4.3 (87)",
    image: "/thumbnail/tiga.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Membangun Bisnis Digital",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Validasi ide bisnis", type: "Video", duration: "16 Menit" },
          { title: "MVP development", type: "Video", duration: "18 Menit" },
          { title: "Growth hacking basics", type: "Video", duration: "20 Menit" },
        ],
      },
      {
        title: "Funding Strategies",
        type: "Video",
        duration: "21 Menit",
      },
      {
        title: "Scaling Digital Business",
        type: "Video",
        duration: "23 Menit",
      },
    ],
  },
  {
    id: "31",
    title: "Leadership & Management",
    instructor: "Dewi Anggraeni\nHR Director",
    price: 280,
    rating: "4.4 (98)",
    image: "/thumbnail/empat.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Modern Leadership Styles",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "Servant leadership", type: "Video", duration: "17 Menit" },
          { title: "Emotional intelligence", type: "Video", duration: "19 Menit" },
          { title: "Decision making frameworks", type: "Video", duration: "21 Menit" },
        ],
      },
      {
        title: "Team Management Techniques",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Conflict Resolution",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "32",
    title: "Business Analytics",
    instructor: "Rudi Hermawan\nData Analyst",
    price: 300,
    rating: "4.2 (92)",
    image: "/thumbnail/lima.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Data-Driven Decision Making",
        type: "Video",
        duration: "24 Menit",
        expanded: true,
        items: [
          { title: "KPI identification", type: "Video", duration: "18 Menit" },
          { title: "Data visualization", type: "Video", duration: "20 Menit" },
          { title: "Dashboard creation", type: "Video", duration: "22 Menit" },
        ],
      },
      {
        title: "Predictive Analytics",
        type: "Video",
        duration: "23 Menit",
      },
      {
        title: "Case Study: Retail Analytics",
        type: "Video",
        duration: "21 Menit",
      },
    ],
  },
  {
    id: "33",
    title: "Negotiation Mastery",
    instructor: "Bambang Sutrisno\nNegotiation Expert",
    price: 260,
    rating: "4.5 (105)",
    image: "/thumbnail/enam.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Strategi Negosiasi Efektif",
        type: "Video",
        duration: "21 Menit",
        expanded: true,
        items: [
          { title: "Preparation framework", type: "Video", duration: "15 Menit" },
          { title: "Win-win techniques", type: "Video", duration: "17 Menit" },
          { title: "Handling objections", type: "Video", duration: "19 Menit" },
        ],
      },
      {
        title: "Cross-Cultural Negotiation",
        type: "Video",
        duration: "20 Menit",
      },
      {
        title: "Salary Negotiation Workshop",
        type: "Video",
        duration: "22 Menit",
      },
    ],
  },
  {
    id: "34",
    title: "Project Management Pro",
    instructor: "Linda Hartati\nPMO Head",
    price: 290,
    rating: "4.3 (96)",
    image: "/thumbnail/tujuh.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Agile Methodology",
        type: "Video",
        duration: "23 Menit",
        expanded: true,
        items: [
          { title: "Scrum framework", type: "Video", duration: "17 Menit" },
          { title: "Kanban system", type: "Video", duration: "19 Menit" },
          { title: "Sprint planning", type: "Video", duration: "21 Menit" },
        ],
      },
      {
        title: "Risk Management",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Stakeholder Management",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
  {
    id: "35",
    title: "Public Speaking Expert",
    instructor: "Ahmad Faisal\nCommunication Coach",
    price: 240,
    rating: "4.6 (115)",
    image: "/thumbnail/delapan.jpeg",
    category: "Bisnis",
    video: [
      {
        title: "Seni Presentasi Efektif",
        type: "Video",
        duration: "22 Menit",
        expanded: true,
        items: [
          { title: "Scrum framework", type: "Video", duration: "17 Menit" },
          { title: "Kanban system", type: "Video", duration: "19 Menit" },
          { title: "Sprint planning", type: "Video", duration: "21 Menit" },
        ],
      },
      {
        title: "Risk Management",
        type: "Video",
        duration: "22 Menit",
      },
      {
        title: "Stakeholder Management",
        type: "Video",
        duration: "20 Menit",
      },
    ],
  },
];
